---
title: 'Dicussion 11: Recommender Systems'
author: "Mahmud Hasan Al Raji"
date: "`r Sys.Date()`"
output: html_document
---

Your task is to analyze an existing recommender system that you find interesting. You should:

# 1. Perform a Scenario Design analysis as described below. Consider whether it makes sense for your selected recommender system to perform scenario design twice, once for the organization (e.g. Amazon.com) and once for the organization’s customers.

It makes a lot of sense for Netflix to perform scenario design twice. It is important for Netflix to perform scenario design on a corporate level to identify which types of shows or movies have high viewership. This will inform what types of shows to license, promote or create. Ultimately the corporate goal for Netflix would be to have the pull of recurring subscribers. In order to have sustainable subscribers Netflix must have some allure for users to stay with Netflix over their competition. Through analysis of viewership of shows Netflix can make appropriate business decisions. The recommender system can identify the genres or types of shows that have high viewership.

On the flip side, the recommender system is useful for the viewer to select and identify the next show/video to consume. The system’s algorithm can promote a multitude of genres, either by last viewed or recommendations based on trending views. Netflix also has an odd tendency to recommend endlessly for one-off trends. (One accidental Korean drama click will result in months of Korean soap opera promotions.)

# 2. Attempt to reverse engineer what you can about the site, from the site interface and any available information that you can find on the Internet or elsewhere.

According to Netflix’s own website, they share how their recommendation system works. They look at factors such as user interaction within the application or the website, or how other members with similar preferences interact with the website or app and details about the show or movie such as their genre, categories actors release years etcetera. They also take into consideration the time of viewership, devices the application is being used on and time spent on the application. On the user level they have a specific way of showing their recommendations. That includes the choice of the recommendation row, the title is presented on the row, and the ranking of those titles within the application. 

# 3. Include specific recommendations about how to improve the site’s recommendation capabilities going forward.

I think a good recommendation for Netflix would be to allow viewers to make tags on movies/shows or for the consumer to create different lists for their favorite movies and TV shows. This could strengthen the algorithm to the user’s preferences as well as allow the corporate level to make decisions on which shows to put their money on. 


# Sources: 

1. Business Insider (Meet the average Netflix user, a Millennial woman without a college degree living in the American suburbs earning less than $50,000 a year: https://www.businessinsider.com/typical-netflix-user-subscriber-demographic-millennial-age-political-views-income-2021-9

2. How Netflix’s Recommendation System Works: https://help.netflix.com/en/node/100639



